import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar'
import Sidebar from '../components/sidebar'
import 'bootstrap/dist/css/bootstrap.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className="bg-blue-200">
        <div className="font-sans text-gray-900 antialiased">
          <div className="min-h-screen flex bg-gray-200">
            <div className="flex-shrink-0 w-64 bg-gray-900">
              <a href="#">
                <div
                  className="flex items-center h-16 px-4 bg-gray-900 text-xl text-white font-medium"
                >
                  <div className="ml-2">bobrtc</div>
                </div>
              </a>
              <div>
                
                <div className="px-6 py-6 text-white">
                  <a href="/app/" className="router-link-exact-active router-link-active">
                    Phonebook
                  </a>
                </div>

                <div className="px-6 py-6 border-t border-gray-700">
                  <h4
                    className="text-sm text-gray-600 uppercase font-bold tracking-widest"
                  >
                    Resources
                  </h4>
                  <ul className="mt-3 text-white">
                    <li className="mt-3">
                      <a href="#" className="">
                        Activity
                      </a>
                    </li>
                    <li className="mt-3">
                      <a href="#" className="">
                        Recordings
                      </a>
                    </li>
                    <li className="mt-3">
                      <a href="#" className="">
                        Settings
                      </a>
                    </li>
                    <li className="mt-3">
                      <a href="#" className="">
                        Help
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            <div className="flex-grow flex flex-col">
              <div
                className="relative shadow-md bg-white flex-shrink-0"

              >
                <div className="flex justify-between items-center h-16 px-12">
                  <div>
                    <div className="relative w-64">
                      <div className="relative z-50">
                        <input
                          type="text"
                          className="block w-full py-2 pl-12 pr-4 bg-gray-200 rounded-full border border-transparent focus:bg-white focus:border-gray-300 focus:outline-none"
                        />
                        <div className="flex items-center absolute left-0 inset-y-0 pl-3">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 24 24"
                            className="h-6 w-6 fill-current text-gray-600"
                          >
                            <path
                              d="M16.32 14.9l5.39 5.4a1 1 0 0 1-1.42 1.4l-5.38-5.38a8 8 0 1 1 1.41-1.41zM10 16a6 6 0 1 0 0-12 6 6 0 0 0 0 12z"
                            ></path>
                          </svg>
                        </div>
                      </div>


                    </div>
                  </div>
                  <div className="flex items-center">
                    <a href="#"><svg
                      xmlns="http://www.w3.org/2000/svg"
                      viewBox="0 0 24 24"
                      className="h-6 w-6"
                    >
                      <path
                        d="M12 21a2 2 0 0 1-1.41-.59l-.83-.82A2 2 0 0 0 8.34 19H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h4a5 5 0 0 1 4 2v16z"
                        className="fill-current text-gray-400"
                      ></path>
                      <path
                        d="M12 21V5a5 5 0 0 1 4-2h4a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1h-4.34a2 2 0 0 0-1.42.59l-.83.82A2 2 0 0 1 12 21z"
                        className="fill-current text-gray-600"
                      ></path></svg
                    ></a>
                    <div className="ml-6">

                      <div className="relative">
                        <button type="button" className="block w-full focus:outline-none">
                          <span className="flex items-center"
                          ><img
                              src="https://www.gravatar.com/avatar/9240e2357dc0b9a4cfd1b109c23af063?d=https%3A%2F%2Fui-avatars.com%2Fapi%2Fmuse"
                              className="h-8 w-8 rounded-full" />
                            <span className="ml-3">muse</span>
                            <svg
                              xmlns="http://www.w3.org/2000/svg"
                              viewBox="0 0 24 24"
                              fill="currentColor"
                              className="h-6 w-6 ml-2 text-gray-600"
                            >
                              <path
                                d="M15.3 9.3a1 1 0 0 1 1.4 1.4l-4 4a1 1 0 0 1-1.4 0l-4-4a1 1 0 0 1 1.4-1.4l3.3 3.29 3.3-3.3z"
                              ></path></svg
                            ></span>
                        </button>

                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="flex-grow flex flex-col">
                <div className="flex-grow">
                  <div className="bg-white">
                    <div className="px-12">
                      <div className="flex justify-between py-6">
                        <div>
                          <div
                            className="flex items-center text-sm text-gray-700 uppercase font-bold tracking-widest"
                          >
                            <p className="mr-4 bg-gray-200 rounded p-2">1337XP</p>
                            <p>300C</p>
                          </div>
                          <div className="flex mt-3">
                            <p className="text-sm font-medium bg-orange-100 p-4 leading-loose">
                              <span className="w-full block mb-2 border-b border-orange-200 pb-2 mb-2 text-orange-400 font-bold uppercase tracking-widest">System Update</span> The ability to add numbers to the BobRTC phonebook requires an XP score above 785XP and your account must be active for an extended period of time. Contact a TLS, Scammer.info or BobRTC moderator for more details.</p>
                          </div>
                        </div>

                      </div>
                    </div>
                  </div>
                  <div className="px-12 py-8 mx-auto max-w-4xl">
                    <div>
                      <div className="flex items-baseline justify-between">
                        <div>
                          <h2 className="text-lg">
                            Welcome To BobRTC!
                          </h2>
                          <div className="mt-2 text-sm text-gray-700">
                            Take your first steps into a serverless future.
                          </div>
                        </div>

                      </div>
                      <div className="mt-4">
                        <div className="px-6 py-4 bg-white shadow-md rounded-lg flex justify-between">
                          <div className="flex justify-between text-sm font-medium uppercase tracking-wide">
                            <svg
                              xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" className="-mt-1 mr-4 h-6 w-6">
                              <path
                                d="M5 8h14a1 1 0 0 1 1 1v11a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V9a1 1 0 0 1 1-1zm1 2v7h12v-7H6z"
                                className="fill-current text-gray-400"
                              ></path>
                              <path
                                d="M6 12a4 4 0 0 1-4-4 1 1 0 0 1 .1-.45l2-4A1 1 0 0 1 5 3h14a1 1 0 0 1 .9.55l2 4c.06.14.1.3.1.45a4 4 0 0 1-7 2.65 3.99 3.99 0 0 1-6 0A3.99 3.99 0 0 1 6 12z"
                                className="fill-current text-gray-600"
                              ></path>

                            </svg>
                            <p>IRS Scam</p>
                          </div>
                          <div
                            className="ml-3 font-semibold text-sm text-gray-600 uppercase tracking-wider"
                          >
                            <a href="#" className=""
                            >+1 (844) 483-4444</a>
                          </div>
                        </div>

                      </div>
                    </div>
                    <div className="mt-4">
                      <div className="px-6 py-4 bg-white shadow-md rounded-lg">
                        <div>
                          <div className="flex items-center">
                            <svg
                              xmlns="http://www.w3.org/2000/svg"
                              viewBox="0 0 24 24"
                              className="h-6 w-6"
                            >
                              <path
                                d="M5 8h14a1 1 0 0 1 1 1v11a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V9a1 1 0 0 1 1-1zm1 2v7h12v-7H6z"
                                className="fill-current text-gray-400"
                              ></path>
                              <path
                                d="M6 12a4 4 0 0 1-4-4 1 1 0 0 1 .1-.45l2-4A1 1 0 0 1 5 3h14a1 1 0 0 1 .9.55l2 4c.06.14.1.3.1.45a4 4 0 0 1-7 2.65 3.99 3.99 0 0 1-6 0A3.99 3.99 0 0 1 6 12z"
                                className="fill-current text-gray-600"
                              ></path>
                            </svg>
                            <div
                              className="ml-3 font-semibold text-sm text-gray-600 uppercase tracking-wider"
                            >
                              <a href="/app/account/billing" className=""
                              >Choose A Billing Plan</a
                              >
                            </div>
                          </div>
                          <div className="mt-3 mb-8 max-w-2xl text-sm text-gray-700">
                            Before creating your first project, you will need to
                            subscribe to a billing plan. It's one, simple monthly
                            fee, regardless of how many projects, deployments,
                            teams, or team members you have.
                            <strong
                            >To choose a plan, visit your
                              <a href="#" className="underline hover:text-gray-900"
                              >account settings</a
                              >.</strong
                            >
                          </div>
                        </div>
                        <div>
                          <div className="flex items-center">
                            <svg
                              xmlns="http://www.w3.org/2000/svg"
                              viewBox="0 0 24 24"
                              className="h-6 w-6"
                            >
                              <path
                                d="M8.23 10.77a7.01 7.01 0 1 1 5 5L11 18H9v2H7v2.03H2V17l6.23-6.23zM17 9a2 2 0 1 0 0-4 2 2 0 0 0 0 4z"
                                className="fill-current text-gray-400"
                              ></path>
                              <path
                                d="M6.2 18.7a1 1 0 1 1-1.4-1.4l4-4a1 1 0 1 1 1.4 1.4l-4 4z"
                                className="fill-current text-gray-600"
                              ></path>
                            </svg>
                            <div
                              className="ml-3 font-semibold text-sm text-gray-600 uppercase tracking-wider"
                            >
                              <a href="/app/team/settings/cloud-providers" className=""
                              >Connect An AWS Account</a
                              >
                            </div>
                          </div>
                          <div className="mt-3 mb-8 max-w-2xl text-sm text-gray-700">
                            To get started,
                            <a
                              href="/app/team/settings/cloud-providers"
                              className="font-bold underline hover:text-gray-900"
                            >you'll need to link an AWS account</a
                            >. Once connected, we will be able to provision and
                            manage your serverless infrastructure while you focus on
                            building something amazing. To learn more about
                            retrieving your AWS credentials, check out
                            <a
                              href="https://docs.test.build/1.0/introduction.html#linking-with-aws"
                              target="_blank"
                              className="font-bold underline"
                            >our documentation</a
                            >.
                          </div>
                        </div>
                        <div className="flex items-center">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 24 24"
                            className="h-6 w-6"
                          >
                            <path
                              d="M3 6l9 4v12l-9-4V6zm14-3v2c0 1.1-2.24 2-5 2s-5-.9-5-2V3c0 1.1 2.24 2 5 2s5-.9 5-2z"
                              className="fill-current text-gray-400"
                            ></path>
                            <polygon
                              points="21 6 12 10 12 22 21 18"
                              className="fill-current text-gray-600"
                            ></polygon>
                          </svg>
                          <div
                            className="ml-3 font-semibold text-sm text-gray-600 uppercase tracking-wider"
                          >
                            Create Your First Project
                          </div>
                        </div>
                        <div className="mt-3 max-w-2xl text-sm text-gray-700">
                          It is organized around projects. Projects can contain as
                          many environments as you wish and each environment
                          receives its very own URL. To create a project,
                          <a
                            href="https://docs.test.build/1.0/introduction.html#installing-the-test-cli"
                            target="_blank"
                            className="font-bold underline"
                          >install the App CLI</a
                          >, login, and run the
                          <code className="bg-gray-200 font-mono text-xs"
                          >test init</code
                          >
                          command. To learn more, check out our documentation.
                        </div>
                        <div className="mt-8 flex items-center">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 24 24"
                            className="h-6 w-6"
                          >
                            <path
                              d="M12 21a2 2 0 0 1-1.41-.59l-.83-.82A2 2 0 0 0 8.34 19H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h4a5 5 0 0 1 4 2v16z"
                              className="fill-current text-gray-400"
                            ></path>
                            <path
                              d="M12 21V5a5 5 0 0 1 4-2h4a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1h-4.34a2 2 0 0 0-1.42.59l-.83.82A2 2 0 0 1 12 21z"
                              className="fill-current text-gray-600"
                            ></path>
                          </svg>
                          <div
                            className="ml-3 font-semibold text-sm text-gray-600 uppercase tracking-wider"
                          >
                            <a href="https://docs.test.build" target="_blank"
                            >Keep Digging Deeper</a
                            >
                          </div>
                        </div>
                        <div className="mt-3 max-w-2xl text-sm text-gray-700">
                          It has
                          <a
                            href="https://docs.test.build"
                            target="_blank"
                            className="font-bold underline hover:text-gray-900"
                          >thorough documentation</a
                          >
                          to show you the ropes. Start digging in to learn how to
                          create projects, deployment environments, manage
                          databases, scale caches, validate certificates, and more.
                        </div>
                      </div>
                    </div>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="vue-portal-target"></div>

      </main>
    </>
  )
}
